version: 2.1

commands:
  test:
    parameters:
      to:
        default: 'world'
        type: string
    steps:
      - run: echo 'hello <<parameters.to>>'

jobs:
  my-test:
    docker:
      - image: cimg/node:17.8.0
    steps:
      - test
      - checkout
      - run:
          command: |
            echo Running test
      - run: node --version

workflows:
  my-workflow:
    jobs:
      - my-test
